language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - composer install --prefer-dist --dev

script:
  - vendor/bin/phpunit
