install-infrastructure:
	echo "install"
	touch log/app.log

uninstall-infrastructure:
	echo "uninstall"
	rm -f log/app.log

run:
	sleep 1
	echo "This is my first condition" >> log/app.log
	sleep 1
	echo "This is my second condition" >> log/app.log
